name: integrazoo
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8

  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.5
  get_it: ^8.0.3
  intl: ^0.19.0
  fl_chart: ^0.71.0
  data_table_2: ^2.6.0
  shared_preferences: ^2.5.3
  flutter_launcher_icons: ^0.14.4

  excel: ^4.0.6
  file_selector: ^1.0.3
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.13

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  linux: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
